  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/en"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/en/portfolio/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/en/about/"

  [[main]]
  name = "Accomplishments"
  weight = 400
  identifier = "accomplishments"

  [[main]]
  name = "Certifications"
  weight = 410
  identifier = "certifications"
  url = "/en/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "Resume"
  weight = 500
  identifier = "resume"
  url = "/en/resume/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/en/contact/"

  [[footer]]
  name = "theme"
  weight = 1
  identifier = "theme"
  url = "/en/theme/"